### PR TITLE
CHANGELOG add for cucumber/cucumber #251

### PR DESCRIPTION
**Pull request by mxygem**
## Summary

CHANGELOG.md add per [cucumber/cucumber #251](https://github.com/cucumber/cucumber/issues/251)

## Details

* Added CHANGELOG.md
* _Note: Symbolic PR as I unintentionally pushed to master._

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Documentation update

### CODE REVIEW

**Comment by d-led** [comment]
looks ok! Who can merge? @mattwynne I seem to have lost the rights to merge. Pull request #2 fixes the build

**Comment by mxygem** [comment]
I can merge, but it'll need to be tomorrow when I'm on a computer. 'Pull requests that have a failing status can’t be merged on a phone.'

Failures don't have anything to do with my work.

**Comment by olleolleolle** [comment]
@d-led There, a build fix, and you _have_ commit bit again.

**Comment by d-led** [comment]
@jaysonesmith @olleolleolle ok! Will read up on cucumber/cucumber#251

**Pull request merged**
